plugins {
    id 'com.android.application'
}

android {
    namespace 'com.marilu.miniflip'
    compileSdk 35

    defaultConfig {
        applicationId 'com.marilu.miniflip'
        minSdk 30
        targetSdk 35
        versionCode 12
        versionName '0.12-irving-os-direct-home'
    }
}

dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
}
